package com.mapr.demo.auditstream.kafka.entity;

public enum FsOperation {
    CHGRP, CHOWN, CHPERM, CREATE, CREATESYM, DELETE, DISABLEAUDIT, ENABLEAUDIT,
    READ, REMOVEXATTR, RENAME, RMDIR, SETATTR, SETXATTR, TRUNCATE, WRITE
}
